config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  mount API::Root => '/api'
  mount GrapeSwaggerRails::Engine => '/docs' if defined? GrapeSwaggerRails

  root :to =>"homes#top"
  get "home/about"=>"homes#about"
  get '/search', to: 'searches#search'
  get 'chat/:id' => 'chats#show', as: 'chat'

  devise_for :users
  resources :books, only: [:index,:show,:edit,:create,:destroy,:update] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end
  resources :users, only: [:index,:show,:edit,:update] do
    resource :relationships, only: [:create, :destroy]
    get 'follows' => 'relationships#follows', as: 'follows'
    get 'followers' => 'relationships#followers', as: 'followers'
    get "search", to: "users#search"
  end
  resources :chats, only: [:create]
  resources :groups do
    get "join" => "groups#join"
    get "new/mail" => "groups#new_mail"
    get "send/mail" => "groups#send_mail"
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorited_books, through: :favorites, source: :book
  has_many :book_comments, dependent: :destroy
  has_many :active_relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :passive_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :follows, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower
  has_many :user_rooms
  has_many :chats
  has_many :group_users
  has_many :groups, through: :group_users, dependent: :destroy
  has_one_attached :profile_image

  validates :name, length: { minimum: 2, maximum: 20 }, uniqueness: true
  validates :introduction, length: { maximum: 50 }

  def get_profile_image
    (profile_image.attached?) ? profile_image : 'no_image.jpg'
  end

  def follow(user_id)
    active_relationships.create(followed_id: user_id)
  end

  def unfollow(user_id)
    active_relationships.find_by(followed_id: user_id).destroy
  end

  def following?(user)
    follows.include?(user)
  end

  def followed?(user)
    followers.include?(user)
  end

  def mutual_follows?(user)
    following?(user) && followed?(user)
  end

  def create_books_day_ago(n)
    books.where(created_at: n.day.ago.all_day)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :ensure_correct_user, only: [:edit, :update]


  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
    @today_book =  @books.created_today
    @yesterday_book = @books.created_yesterday
    @this_week_book = @books.created_this_week
    @last_week_book = @books.created_last_week
    set_chartlabels
    set_chartdatas
  end

  def index
    @users = User.all
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    if @user.update(user_params)
      redirect_to user_path(@user), notice: "You have updated user successfully."
    else
      render "edit"
    end
  end

  def search
    @user = User.find(params[:user_id])
    @books = @user.books
    if params[:created_at].blank?
      @search_books = "日付を選択してください"
    else
      create_at = params[:created_at]
      @search_books = @books.where(['created_at LIKE ? ', "#{create_at}%"])
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

  def ensure_correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user)
    end
  end

  def set_chartlabels
    @chartlabels = []
    for n in 0..6 do
      @chartlabels << view_context.day_ago(n)
    end
    @chartlabels = @chartlabels.reverse.to_json.html_safe
  end

  def set_chartdatas
    @chartdatas = []
    for n in 0..6 do
      @chartdatas << @user.create_books_day_ago(n).count
    end
    @chartdatas = @chartdatas.reverse
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def day_ago(n)
    n == 0 ? "今日" : "#{n}日前"
  end
end

app/views/users/_index.html.erb
<table class='table'>
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% users.each do |user| %>
      <tr>
        <td><%= image_tag user.get_profile_image, size: '50x50' %></td>
        <td><%= user.name %></td>
        <td>フォロー数: <%= user.follows.count %></td>
        <td>フォロワー数: <%= user.followers.count %></td>
        <td>
          <% if user != current_user %>
            <% if current_user.following?(user) %>
              <%= link_to "フォロー外す", user_relationships_path(user.id), method: :delete %>
            <% else %>
              <%= link_to "フォローする", user_relationships_path(user.id), method: :post %>
            <% end %>
          <% end %>
        </td>
        <td><%= link_to 'Show', user, class: "user_#{user.id}" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/_info.html.erb
<table class='table'>
  <tr><%= image_tag user.get_profile_image, size:'100x100' %></tr>
  <tr>
	  <th>name</th>
	  <th><%= user.name %></th>
  </tr>
  <tr>
	  <th>introduction</th>
	  <th><%= user.introduction %></th>
  </tr>
  <tr>
	  <th>follows</th>
	  <th>
      <%= link_to user_follows_path(user) do %>
        <%= user.follows.count %>
      <% end %>
    </th>
  </tr>
  <tr>
	  <th>followers</th>
    <th>
      <%= link_to user_followers_path(user) do %>
        <%= user.followers.count %>
      <% end %>
    </th>
  </tr>
</table>

<div class='row'>
  <%= link_to edit_user_path(user), class: "btn btn-outline-secondary btn-block edit_user_#{user.id}" do %>
    <i class="fas fa-user-cog"></i>
  <% end %>
</div>

<% if user != current_user %>
  <div class="row mt-2">
    <% if current_user.following?(user) %>
      <%= link_to "フォロー外す", user_relationships_path(user.id), method: :delete, class:"btn btn-info" %>
    <% else %>
      <%= link_to "フォローする", user_relationships_path(user.id), method: :post, class:"btn btn-success" %>
    <% end %>
    <% if current_user.mutual_follows?(user) %>
      <div class="mt-2 ml-2"><%= link_to 'chatを始める', chat_path(user.id)%></div>
    <% end %>
  </div>
<% end %>

app/views/users/_search.html.erb
<h4>検索結果</h4>
<table class="table table-bordered">
  <tr>
    <th>投稿数</th>
  </tr>
  <tr>
    <td><%= search_books.count %></td>
  </tr>
</table>

app/views/users/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <h2>User info</h2>
    <%= form_with model:@user, local:true do |f| %>
      <%= render 'layouts/errors', obj: @user %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control name" %>
      </div>
     <div class="form-group">
        <%= f.label :image %>
        <%= f.file_field :profile_image, class: "form-control-file user_image", accept: 'image/*' %>
      </div>
      <div class="form-group">
        <%= f.label :introduction %>
        <%= f.text_area :introduction, class: "form-control introduction" %>
      </div>
      <div class="form-group">
        <%= f.submit class: 'btn btn-secondary' %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'info', user: current_user %>

      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Users</h2>
      <div><%=link_to "グループを作成する",new_group_path %> | <%=link_to "グループ一覧",groups_path %></div>
      <%= render 'index',users: @users %>
    </div>
  </div>
</div>

app/views/users/search.js.erb
$("#search_result").html("<%= j(render 'search', search_books: @search_books) %>");

app/views/users/show.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'info', user: @user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <div class="user_show_books">
        <h2>Books</h2>
        <%= render 'books/index',books: @books %>
      </div>
      <div class="user_show_book_counts">
        <table class="table table-bordered">
          <tr>
            <th>今日の投稿数</th>
            <th>前日の投稿数</th>
            <th>前日比</th>
          </tr>
          <tr>
            <td><%= @today_book.count %></td>
            <td><%= @yesterday_book.count %></td>
            <td>
              <% if @yesterday_book.count != 0 %>
                <% @the_day_before = @today_book.count / @yesterday_book.count.to_f %>
                <%= (@the_day_before * 100).round %>%
              <% end %>
            </td>
          </tr>
        </table>
        <table class="table table-bordered">
          <tr>
            <th>今週の投稿数</th>
            <th>前週の投稿数</th>
            <th>前週比</th>
          </tr>
          <tr>
            <td><%= @this_week_book.count %></td>
            <td><%= @last_week_book.count %></td>
            <td>
              <% if @last_week_book.count != 0 %>
                <% @the_week_before = @this_week_book.count / @last_week_book.count.to_f %>
                <%= (@the_week_before * 100).round %>%
              <% end %>
            </td>
          </tr>
        </table>
      </div>

      <div class="user_show_book_counts_for_one_week">
        <h3>７日間分の投稿数</h3>
        <table class="table table-bordered">
          <tr>
            <th><%= day_ago(6) %></th>
            <th><%= day_ago(5) %></th>
            <th><%= day_ago(4) %></th>
            <th><%= day_ago(3) %></th>
            <th><%= day_ago(2) %></th>
            <th><%= day_ago(1) %></th>
            <th><%= day_ago(0) %></th>
          </tr>
          <tr>
            <td><%= @user.create_books_day_ago(6).count %></td>
            <td><%= @user.create_books_day_ago(5).count %></td>
            <td><%= @user.create_books_day_ago(4).count %></td>
            <td><%= @user.create_books_day_ago(3).count %></td>
            <td><%= @user.create_books_day_ago(2).count %></td>
            <td><%= @user.create_books_day_ago(1).count %></td>
            <td><%= @user.create_books_day_ago(0).count %></td>
          </tr>
        </table>
      </div>

      <div class="user_show_search_books_count">
        <%= form_with url: user_search_path(@user), method: :get, local: false do |f| %>
          <%= f.date_field :created_at %>
          <%= f.submit '検索', class: 'btn btn-primary'  %>
        <% end %>

        <div id="search_result">
          <% if @search_books.present? %>
            <%= render 'search', search_books: @search_books %>
          <% end %>
        </div>
      </div>

      <div class="user_show_chart">
        <canvas id="myChart" width="200" height="100"> </canvas>
      </div>
      <script>
          var ctx = document.getElementById("myChart").getContext('2d');
          var myChart = new Chart(ctx, {
              type: 'bar',
              data: {
                  labels: <%= @chartlabels %>,
                  datasets: [{
                      label: "投稿した本の数",
                      data: <%= @chartdatas %>,
                      backgroundColor: 'rgba(255, 80, 120, 0.2)',
                      borderColor: 'rgba(255, 80, 120, 1.0)',
                      lineTension: 0.3,
                      type: 'line'
                  }]
              },
              options: {
                scales: {
                    y: {
                      display: true,
                      suggestedMin: 0,
                      suggestedMax: 10,
                      beginAtZero: true,
                      ticks: {
                        stepSize: 1,
                      }
                    }
                }
              }
          });
      </script>

    </div>
  </div>
</div>